### ISSUE TITLE
[BUG] When you are using multiple mods that adds tooltip to the item the order is wrong.

### ISSUE THREAD

**Issue by murao-kun** [Darkhax-Minecraft/Tool-Stats#21]
Recently I tested this mod with [DurabilityTooltip](https://github.com/SuperMartijn642/DurabilityTooltip) and got issue that Durability Tooltip showing higher than Tool Stats Tooltip. Author found the solution by setting theirs ItemTooltipEvent to LOWEST. This is fixing the issue, but to have no conflicts in the future with other mods, he suggesting you to set yours to HIGHEST.
![image](https://user-images.githubusercontent.com/110398598/185093767-e7211b47-ad5f-44ff-baae-9a0f274ae435.png)
https://github.com/SuperMartijn642/DurabilityTooltip/issues/7

**Comment by Darkhax** [comment]
Thanks for reporting this issue. I currently use the same code on Forge and Fabric so I don't have a way to set the Forge specific priority order but this is a bug and I will look into fixing this soon.

**Comment by murao-kun** [comment]
The issue was fixed on the other mod side and after some testing I didn't found any new issues with that. It is up to you to close it or fix it for the future incompatible cases. If you are considering to rise it still, I suggest to left the highest option in case of other mod really needing that.

**Comment by markygnlg** [comment]
Since this is still open, I'll add that with my modlist I've found that 'Advanced Tootips' (F3+H .. or via the Optifine 'video -> other' setting) will block ToolStats-Forge-1.19.2-12.0.2 from showing durability, ie:

![image](https://user-images.githubusercontent.com/62978705/220254203-4be0242a-8ea0-4404-a6f9-a59f8803f77b.png)

![image](https://user-images.githubusercontent.com/62978705/220254236-77f3ff91-b02d-42f8-b878-876ec1b9bec2.png)

I've not used DurabilityTooltip (but I use supermartijn642 mods for chunkloaders & landmines) since I prefer ToolStats because it shows durability in JEI /NEI /etc BEFORE I build a tool; with the settings:

  "showEnchantability": true,
  "alwaysShowEnchantability": true,
  "showRepairCost": true,
  "alwaysShowRepairCost": true,
  "showHarvestLevel": true,
  "showEfficiency": true,
  "showDurability": true,
  "alwaysShowDurability": true

**Comment by Darkhax** [comment]
The initial issue has finally been fixed on 1.19.4. 

@markygnlg Durability is intentionally not displayed when F3+H is enabled because mojang has their own durability tooltip that is displayed.
