### ISSUE TITLE
Change in Mining Efficiency

### ISSUE THREAD

**Issue by zanecek** [Darkhax-Minecraft/Tool-Stats#34]
MC 1.16.5 ToolStats 6.1.6 (last): all swords have mining efficiency 15
MC 1.16.5 ToolStats 6.0.5: swords have mining efficiency according to their material (f.e. 4  for stone, 8 for diamond, 12 for gold,...)

What version is correct?
Is it necessary to show mining efficiency for swords? It disturbs.

**Comment by Darkhax** [comment]
The 6.1.6 update is correct, but not as correct as it could be. Mining efficiency is no longer a static value in Minecraft and this update changes how we read the value to better reflect what players encounter. Swords specifically base their mining efficiency on the block being mined rather than the material of the sword. For example cobwebs are 15, 50+ other blocks are 1.5, and everything else is 1. 16.0.2 has changed this to display 1.5 instead of 15 which is a special edge case.

While this stat isn't very useful in vanilla there are modded scenarios where this can be useful, for example modded swords can and do stray from vanilla's logic and this would allow players to compare swords based on this stat. These scenarios are not very common though, so I have added a config option in 16.0.2 that disables this by default. I am not planning to backport this to older versions as you can already disable them using a datapack by adding the swords to the `ignore_dig_speed` tag.

**Comment by zanecek** [comment]
I tried it and I'm afraid that in version 1.16.5 the tags are not yet implemented...
