### ISSUE TITLE
[Suggestion] make harvest level and dig speed show only on appropriate tools

### ISSUE THREAD

**Issue by memphismc** [Darkhax-Minecraft/Tool-Stats#35]
Digging speed should only be shown on pickaxes while harvest level should only be shown on hoes or whatever its for

**Comment by Darkhax** [comment]
This is intentional and not a bug or oversight. Swords are the correct tool for breaking over 50 blocks in the vanilla game such as pumpkins, melons, and cobwebs, meaning they have a digging speed value to display. Harvest Level is a property of all tiered tools and is used to determine the materials a tool can mine while still getting drops. For example a stone pickaxe can not mine diamond ore and still get the drops because it's harvest level is not high enough.
